// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: jutsu/jutsu.proto

package jutsu

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jutsu_jutsu_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jutsu_jutsu_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_jutsu_jutsu_proto_rawDescGZIP(), []int{0}
}

type NinshuReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool    `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Reply   *string `protobuf:"bytes,2,opt,name=reply,proto3,oneof" json:"reply,omitempty"`
}

func (x *NinshuReply) Reset() {
	*x = NinshuReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jutsu_jutsu_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NinshuReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NinshuReply) ProtoMessage() {}

func (x *NinshuReply) ProtoReflect() protoreflect.Message {
	mi := &file_jutsu_jutsu_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NinshuReply.ProtoReflect.Descriptor instead.
func (*NinshuReply) Descriptor() ([]byte, []int) {
	return file_jutsu_jutsu_proto_rawDescGZIP(), []int{1}
}

func (x *NinshuReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *NinshuReply) GetReply() string {
	if x != nil && x.Reply != nil {
		return *x.Reply
	}
	return ""
}

type HelloRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ping string `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jutsu_jutsu_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jutsu_jutsu_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_jutsu_jutsu_proto_rawDescGZIP(), []int{2}
}

func (x *HelloRequest) GetPing() string {
	if x != nil {
		return x.Ping
	}
	return ""
}

type HelloReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pong string `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jutsu_jutsu_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_jutsu_jutsu_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_jutsu_jutsu_proto_rawDescGZIP(), []int{3}
}

func (x *HelloReply) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

type ConnectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jutsu_jutsu_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jutsu_jutsu_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_jutsu_jutsu_proto_rawDescGZIP(), []int{4}
}

func (x *ConnectRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

var File_jutsu_jutsu_proto protoreflect.FileDescriptor

var file_jutsu_jutsu_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6a, 0x75, 0x74, 0x73, 0x75, 0x2f, 0x6a, 0x75, 0x74, 0x73, 0x75, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6a, 0x75, 0x74, 0x73, 0x75, 0x22, 0x0e, 0x0a, 0x0c, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4c, 0x0a, 0x0b, 0x4e, 0x69,
	0x6e, 0x73, 0x68, 0x75, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x12, 0x19, 0x0a, 0x05, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x88, 0x01, 0x01, 0x42, 0x08,
	0x0a, 0x06, 0x5f, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x22, 0x0a, 0x0c, 0x48, 0x65, 0x6c, 0x6c,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x22, 0x20, 0x0a, 0x0a,
	0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f,
	0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x22, 0x20,
	0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70,
	0x32, 0xec, 0x01, 0x0a, 0x07, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x12, 0x34, 0x0a, 0x08,
	0x50, 0x69, 0x6e, 0x67, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x13, 0x2e, 0x6a, 0x75, 0x74, 0x73, 0x75,
	0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e,
	0x6a, 0x75, 0x74, 0x73, 0x75, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x12, 0x37, 0x0a, 0x0a, 0x44, 0x72, 0x6f, 0x70, 0x41, 0x6e, 0x63, 0x68, 0x6f, 0x72,
	0x12, 0x13, 0x2e, 0x6a, 0x75, 0x74, 0x73, 0x75, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x6a, 0x75, 0x74, 0x73, 0x75, 0x2e, 0x4e, 0x69,
	0x6e, 0x73, 0x68, 0x75, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x0b, 0x52,
	0x61, 0x69, 0x73, 0x65, 0x41, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x12, 0x13, 0x2e, 0x6a, 0x75, 0x74,
	0x73, 0x75, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x12, 0x2e, 0x6a, 0x75, 0x74, 0x73, 0x75, 0x2e, 0x4e, 0x69, 0x6e, 0x73, 0x68, 0x75, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x54, 0x6f, 0x12, 0x15, 0x2e, 0x6a, 0x75, 0x74, 0x73, 0x75, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x6a, 0x75, 0x74, 0x73,
	0x75, 0x2e, 0x4e, 0x69, 0x6e, 0x73, 0x68, 0x75, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42,
	0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x6c,
	0x72, 0x6f, 0x64, 0x72, 0x69, 0x67, 0x75, 0x65, 0x73, 0x2f, 0x6e, 0x69, 0x6e, 0x73, 0x68, 0x75,
	0x64, 0x2f, 0x6a, 0x75, 0x74, 0x73, 0x75, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_jutsu_jutsu_proto_rawDescOnce sync.Once
	file_jutsu_jutsu_proto_rawDescData = file_jutsu_jutsu_proto_rawDesc
)

func file_jutsu_jutsu_proto_rawDescGZIP() []byte {
	file_jutsu_jutsu_proto_rawDescOnce.Do(func() {
		file_jutsu_jutsu_proto_rawDescData = protoimpl.X.CompressGZIP(file_jutsu_jutsu_proto_rawDescData)
	})
	return file_jutsu_jutsu_proto_rawDescData
}

var file_jutsu_jutsu_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_jutsu_jutsu_proto_goTypes = []interface{}{
	(*EmptyRequest)(nil),   // 0: jutsu.EmptyRequest
	(*NinshuReply)(nil),    // 1: jutsu.NinshuReply
	(*HelloRequest)(nil),   // 2: jutsu.HelloRequest
	(*HelloReply)(nil),     // 3: jutsu.HelloReply
	(*ConnectRequest)(nil), // 4: jutsu.ConnectRequest
}
var file_jutsu_jutsu_proto_depIdxs = []int32{
	2, // 0: jutsu.Cluster.PingNode:input_type -> jutsu.HelloRequest
	0, // 1: jutsu.Cluster.DropAnchor:input_type -> jutsu.EmptyRequest
	0, // 2: jutsu.Cluster.RaiseAnchor:input_type -> jutsu.EmptyRequest
	4, // 3: jutsu.Cluster.ConnectTo:input_type -> jutsu.ConnectRequest
	3, // 4: jutsu.Cluster.PingNode:output_type -> jutsu.HelloReply
	1, // 5: jutsu.Cluster.DropAnchor:output_type -> jutsu.NinshuReply
	1, // 6: jutsu.Cluster.RaiseAnchor:output_type -> jutsu.NinshuReply
	1, // 7: jutsu.Cluster.ConnectTo:output_type -> jutsu.NinshuReply
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_jutsu_jutsu_proto_init() }
func file_jutsu_jutsu_proto_init() {
	if File_jutsu_jutsu_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_jutsu_jutsu_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jutsu_jutsu_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NinshuReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jutsu_jutsu_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jutsu_jutsu_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jutsu_jutsu_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_jutsu_jutsu_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_jutsu_jutsu_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jutsu_jutsu_proto_goTypes,
		DependencyIndexes: file_jutsu_jutsu_proto_depIdxs,
		MessageInfos:      file_jutsu_jutsu_proto_msgTypes,
	}.Build()
	File_jutsu_jutsu_proto = out.File
	file_jutsu_jutsu_proto_rawDesc = nil
	file_jutsu_jutsu_proto_goTypes = nil
	file_jutsu_jutsu_proto_depIdxs = nil
}
